#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "tokens.h"

// External declarations for flex-generated functions
extern int yylex(void);
extern FILE* yyin;
extern char* yytext;

void yyerror(const char* msg) {
    fprintf(stderr, "Error: %s at line %d\n", msg, yylineno);
}

void print_header() {
    printf("ROADMAP COMPILER - PHASE 1\n");
    printf(" LEXICAL ANALYZER\n");
    printf(" Input:  test.txt (source code)\n");
    printf(" Output: tokens.txt (token stream for Phase 2)\n");
}

void print_input_content(const char* filename) {
    printf("INPUT FILE: %s\n", filename);
    printf("\n");
    
    FILE* file = fopen(filename, "r");
    if (!file) {
        printf(" [ERROR: Cannot read file]\n");
        printf("\n\n");
        return;
    }
    
    char line[256];
    int line_num = 1;
    while (fgets(line, sizeof(line), file)) {
        // Remove newline for cleaner display
        line[strcspn(line, "\n")] = 0;
        printf(" %2d: %s\n", line_num++, line);
    }
    fclose(file);
    
    printf("\n");
    printf("\n\n");
}

void print_token_header() {
    printf("TOKENIZATION PROCESS\n");
    printf("\n");
    printf(" %-4s %-12s %-15s %-6s %s\n", "Line", "Token Type", "Lexeme", "Value", "Description");
    printf(" ────────────────────────────────────────────────────────────────────\n");
}

void print_token_line(int line, const char* token_type, const char* lexeme, const char* value, const char* description) {
    printf(" %-4d %-12s %-15s %-6s %s\n", line, token_type, lexeme, value ? value : "─", description);
}

void print_token_footer(int token_count) {
    printf("\n");
    printf(" Total tokens generated: %d\n", token_count);
    printf("\n\n");
}

void print_output_file_info(const char* filename, int token_count) {
    printf("OUTPUT FILE: %s\n", filename);
    printf("\n");
    printf("Tokens: %d\n", token_count);
    printf("\n\n");
}


const char* get_token_description(TokenType type) {
    switch (type) {
        case IDENTIFIER: return "Variable/Symbol";
        case ASSIGN: return "Assignment operator";
        case T_TRUE: return "Boolean literal (true)";
        case T_FALSE: return "Boolean literal (false)";
        case AND: return "Logical AND";
        case OR: return "Logical OR";
        case NOT: return "Logical NOT";
        case XOR: return "Logical XOR";
        case XNOR: return "Logical XNOR";
        case IMPLIES: return "Implication";
        case IFF: return "If and only if";
        case EQUIV: return "Equivalence";
        case EXISTS: return "Existential quantifier";
        case FORALL: return "Universal quantifier";
        case IF: return "Conditional keyword";
        case IFF_KEYWORD: return "Biconditional keyword";
        case LPAREN: return "Left parenthesis";
        case RPAREN: return "Right parenthesis";
        default: return "Unknown token";
    }
}

int tokenize_file_to_tokens(const char* input_filename, const char* output_filename) {
    // Open input file
    FILE* input_file = fopen(input_filename, "r");
    if (!input_file) {
        printf("ERROR: Cannot open input file '%s'\n\n", input_filename);
        return -1;
    }
    fclose(input_file);
    
    // Open output file for tokens
    FILE* token_file = fopen(output_filename, "w");
    if (!token_file) {
        printf("ERROR: Cannot create output file '%s'\n\n", output_filename);
        return -1;
    }
    
    // Set input for flex
    FILE* old_yyin = yyin;
    yyin = fopen(input_filename, "r");
    if (!yyin) {
        printf("ERROR: Cannot reopen input file for tokenization\n\n");
        fclose(token_file);
        return -1;
    }
    
    // Reset line number
    extern int yylineno;
    yylineno = 1;
    
    // Write header to token file
    fprintf(token_file, "# Tokens generated by Phase 1 Lexical Analyzer\n");
    fprintf(token_file, "# Input file: %s\n", input_filename);
    fprintf(token_file, "#\n");
    
    // Print tokenization header
    print_token_header();
    
    // Tokenize input and write to file
    int token;
    int token_count = 0;
    
    while ((token = yylex()) != 0) {
        if (token == INVALID_TOKEN) {
            print_token_line(yylineno, "INVALID", yytext, "ERROR", "Unrecognized character");
            fprintf(token_file, "INVALID_TOKEN %s\n", yytext);
            break;
        }
        
        const char* token_name = token_type_to_string(token);
        const char* description = get_token_description(token);
        char value_str[20] = "─";
        
        // Handle different token types
        if (token == T_TRUE || token == T_FALSE) {
            snprintf(value_str, sizeof(value_str), "%s", yylval.bool_val ? "true" : "false");
            fprintf(token_file, "%s %s %d\n", token_name, yytext, yylval.bool_val);
        } else if (token == IDENTIFIER) {
            snprintf(value_str, sizeof(value_str), "%s", yytext);
            fprintf(token_file, "%s %s\n", token_name, yytext);
        } else {
            fprintf(token_file, "%s %s\n", token_name, yytext);
        }
        
        print_token_line(yylineno, token_name, yytext, 
                        (token == T_TRUE || token == T_FALSE || token == IDENTIFIER) ? value_str : NULL, 
                        description);
        
        token_count++;
    }
    
    // Write footer to token file
    fprintf(token_file, "#\n");
    fprintf(token_file, "# Total tokens: %d\n", token_count);
    fprintf(token_file, "EOF\n");
    
    // Cleanup
    fclose(yyin);
    yyin = old_yyin;
    fclose(token_file);
    
    print_token_footer(token_count);
    
    return token_count;
}

void create_default_test_file() {
    FILE* test_file = fopen("test.txt", "w");
    if (test_file) {
        fprintf(test_file, "B = TRUE\n");
        fprintf(test_file, "C = FALSE\n");
        fprintf(test_file, "B OR C\n");
        fclose(test_file);
        
        printf("CREATING DEFAULT TEST FILE\n");
        printf("\n");
        printf(" Created: test.txt\n");
        printf(" Content: logical expressions\n");
        printf("\n");
        printf("\n\n");
    } else {
        printf("ERROR: Cannot create test.txt file\n\n");
    }
}

int main() {
    print_header();
    
    // Check if test.txt exists, if not create it
    FILE* test_file = fopen("test.txt", "r");
    if (!test_file) {
        create_default_test_file();
    } else {
        fclose(test_file);
    }
    
    // Display input file content
    print_input_content("test.txt");
    
    // Process the test file
    int token_count = tokenize_file_to_tokens("test.txt", "tokens.txt");
    
    if (token_count >= 0) {
        // Display output file information
        print_output_file_info("tokens.txt", token_count);
        
        
        return 0;
    } else {
        printf("Phase 1 failed. Please check your input file.\n\n");
        return 1;
    }
}